In [1]:
## import libs
import pandas as pd 
import numpy as np

In [2]:
## take dataset
dataset_og=pd.read_csv('train.csv')
dataset=dataset_og.copy()
dataset

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [3]:
## lets focus on Categorical Null Values
features_cat_na=[feature for feature in dataset.columns if dataset[feature].dtype=='O'and dataset[feature].isnull().sum()>1]
features_cat_na
for feature in features_cat_na:print(f"{feature} has {np.round(dataset[feature].isnull().mean(),4)}")

Alley has 0.9377
MasVnrType has 0.0055
BsmtQual has 0.0253
BsmtCond has 0.0253
BsmtExposure has 0.026
BsmtFinType1 has 0.0253
BsmtFinType2 has 0.026
FireplaceQu has 0.4726
GarageType has 0.0555
GarageFinish has 0.0555
GarageQual has 0.0555
GarageCond has 0.0555
PoolQC has 0.9952
Fence has 0.8075
MiscFeature has 0.963

In [4]:
def replace_cat_features(dataset,features_with_na):
    data=dataset.copy()
    data[features_with_na]=data[features_with_na].fillna('Missing')
    return data

In [5]:
dataset=replace_cat_features(dataset,features_cat_na)
dataset[features_cat_na].isnull().sum()

Alley           0
MasVnrType      0
BsmtQual        0
BsmtCond        0
BsmtExposure    0
BsmtFinType1    0
BsmtFinType2    0
FireplaceQu     0
GarageType      0
GarageFinish    0
GarageQual      0
GarageCond      0
PoolQC          0
Fence           0
MiscFeature     0
dtype: int64

In [6]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,...,0,Missing,Missing,Missing,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,...,0,Missing,Missing,Missing,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,...,0,Missing,Missing,Missing,0,12,2008,WD,Normal,250000

In [7]:
features_num_na=[feature for feature in dataset.columns if dataset[feature].isnull().sum()>1 and dataset[feature].dtypes!='O']

In [8]:
for feature in features_num_na:
    print("{}: {}% missing value".format(feature,np.round(dataset[feature].isnull().mean(),4)))

LotFrontage: 0.1774% missing value
MasVnrArea: 0.0055% missing value
GarageYrBlt: 0.0555% missing value

In [9]:
for feature in features_num_na:
    median_value=dataset[feature].median()
    dataset[feature+'nan']=np.where(dataset[feature].isnull(),1,0)
    dataset[feature].fillna(median_value,inplace=True)

In [10]:
dataset[features_num_na].isnull().sum()

LotFrontage    0
MasVnrArea     0
GarageYrBlt    0
dtype: int64

In [11]:
dataset.head(10)

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,250000,0,0,0
5,6,50,RL,85.0,14115,Pave,Missing,IR1,Lvl,AllPub,...,Shed,700,10,2009,WD,Normal,143000,0,0,0
6,7,20,RL,75.0,10084,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,8,2007,WD,Normal,307000,0,0,0
7,8,60,RL,69.0,10382,Pave,Missing,IR1,Lvl,AllPub,...,Shed,350,11,2009,WD,Normal,200000,1,0,0
8,9,50,RM,51.0,6120,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,4,2008,WD,Abnorml,129900,0,0,0
9,10,190,RL,50.0,7420,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,1,2008,WD,Normal,118000,0,0,0

In [12]:
## temporal variables
for feature in ['YearBuilt','YearRemodAdd','GarageYrBlt']:
    dataset[feature]=dataset['YrSold']-dataset[feature]

In [13]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,65.0,8450,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,208500,0,0,0
1,2,20,RL,80.0,9600,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,181500,0,0,0
2,3,60,RL,68.0,11250,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,223500,0,0,0
3,4,70,RL,60.0,9550,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,140000,0,0,0
4,5,60,RL,84.0,14260,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,250000,0,0,0

In [14]:
dataset[['YearBuilt','YearRemodAdd','GarageYrBlt']].head()

   YearBuilt  YearRemodAdd  GarageYrBlt
0          5             5          5.0
1         31            31         31.0
2          7             6          7.0
3         91            36          8.0
4          8             8          8.0

In [15]:
features_num=[feature for feature in dataset.columns if dataset[feature].dtype!='O']

In [16]:
features_num

['Id',
 'MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'MasVnrArea',
 'BsmtFinSF1',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'TotRmsAbvGrd',
 'Fireplaces',
 'GarageYrBlt',
 'GarageCars',
 'GarageArea',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SalePrice',
 'LotFrontagenan',
 'MasVnrAreanan',
 'GarageYrBltnan']

In [32]:
for feature in features_num:print(feature,dataset[feature].min())

Id 1
MSSubClass 20
LotFrontage 21.0
LotArea 1300
OverallQual 1
OverallCond 1
YearBuilt 0
YearRemodAdd -1
MasVnrArea 0.0
BsmtFinSF1 0
BsmtFinSF2 0
BsmtUnfSF 0
TotalBsmtSF 0
1stFlrSF 334
2ndFlrSF 0
LowQualFinSF 0
GrLivArea 334
BsmtFullBath 0
BsmtHalfBath 0
FullBath 0
HalfBath 0
BedroomAbvGr 0
KitchenAbvGr 0
TotRmsAbvGrd 2
Fireplaces 0
GarageYrBlt 0.0
GarageCars 0
GarageArea 0
WoodDeckSF 0
OpenPorchSF 0
EnclosedPorch 0
3SsnPorch 0
ScreenPorch 0
PoolArea 0
MiscVal 0
MoSold 1
YrSold 2006
SalePrice 34900
LotFrontagenan 0
MasVnrAreanan 0
GarageYrBltnan 0

In [37]:
log_num_features=[feature for feature in features_num if dataset[feature].min()>0 and feature not in ['Id']and 'Yr'not in feature and 'Year' not in feature]

In [38]:
log_num_features

['MSSubClass',
 'LotFrontage',
 'LotArea',
 'OverallQual',
 'OverallCond',
 '1stFlrSF',
 'GrLivArea',
 'TotRmsAbvGrd',
 'MoSold',
 'SalePrice']

In [39]:
num_features=['LotFrontage', 'LotArea', '1stFlrSF', 'GrLivArea', 'SalePrice']

for feature in num_features:
    dataset[feature]=np.log(dataset[feature])

In [40]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,4.174387,9.041922,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,12.247694,0,0,0
1,2,20,RL,4.382027,9.169518,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,12.109011,0,0,0
2,3,60,RL,4.219508,9.328123,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,12.317167,0,0,0
3,4,70,RL,4.094345,9.164296,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,11.849398,0,0,0
4,5,60,RL,4.430817,9.565214,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,12.429216,0,0,0

In [41]:
categorical_features=[feature for feature in dataset.columns if dataset[feature].dtype=='O']

In [43]:
for feature in categorical_features:
    temp=dataset.groupby(feature)['SalePrice'].count()/len(dataset)
    temp_df=temp[temp>0.01].index
    dataset[feature]=np.where(dataset[feature].isin(temp_df),dataset[feature],'Rare_var')

In [49]:
dataset.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice,LotFrontagenan,MasVnrAreanan,GarageYrBltnan
0,1,60,RL,4.174387,9.041922,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,2,2008,WD,Normal,12.247694,0,0,0
1,2,20,RL,4.382027,9.169518,Pave,Missing,Reg,Lvl,AllPub,...,Missing,0,5,2007,WD,Normal,12.109011,0,0,0
2,3,60,RL,4.219508,9.328123,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,9,2008,WD,Normal,12.317167,0,0,0
3,4,70,RL,4.094345,9.164296,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,2,2006,WD,Abnorml,11.849398,0,0,0
4,5,60,RL,4.430817,9.565214,Pave,Missing,IR1,Lvl,AllPub,...,Missing,0,12,2008,WD,Normal,12.429216,0,0,0

In [55]:
for feature in categorical_features:
    labels_ordered=dataset.groupby([feature])['SalePrice'].mean().sort_values().index
    print(labels_ordered)

Index(['Rare_var', 'RM', 'RH', 'RL', 'FV'], dtype='object', name='MSZoning')
Index(['Rare_var', 'Pave'], dtype='object', name='Street')
Index(['Grvl', 'Pave', 'Missing'], dtype='object', name='Alley')
Index(['Reg', 'IR1', 'Rare_var', 'IR2'], dtype='object', name='LotShape')
Index(['Bnk', 'Lvl', 'Low', 'HLS'], dtype='object', name='LandContour')
Index(['Rare_var', 'AllPub'], dtype='object', name='Utilities')
Index(['Inside', 'Corner', 'FR2', 'Rare_var', 'CulDSac'], dtype='object', name='LotConfig')
Index(['Gtl', 'Mod', 'Rare_var'], dtype='object', name='LandSlope')
Index(['IDOTRR', 'MeadowV', 'BrDale', 'BrkSide', 'OldTown', 'Edwards',
       'Sawyer', 'SWISU', 'NAmes', 'Mitchel', 'SawyerW', 'Rare_var', 'NWAmes',
       'Gilbert', 'CollgCr', 'Blmngtn', 'Crawfor', 'ClearCr', 'Somerst',
       'Timber', 'StoneBr', 'NridgHt', 'NoRidge'],
      dtype='object', name='Neighborhood')
Index(['Artery', 'Feedr', 'Norm', 'Rare_var', 'RRAn', 'PosN'], dtype='object', name='Condition1')
Index(['Rare_var', 'Norm'], dtype='object', name='Condition2')
Index(['2fmCon', 'Twnhs', 'Duplex', '1Fam', 'TwnhsE'], dtype='object', name='BldgType')
Index(['SFoyer', '1.5Fin', 'Rare_var', '1Story', 'SLvl', '2Story'], dtype='object', name='HouseStyle')
Index(['Gable', 'Rare_var', 'Hip'], dtype='object', name='RoofStyle')
Index(['CompShg', 'Rare_var'], dtype='object', name='RoofMatl')
Index(['AsbShng', 'Rare_var', 'Wd Sdng', 'WdShing', 'MetalSd', 'Stucco',
       'HdBoard', 'Plywood', 'BrkFace', 'CemntBd', 'VinylSd'],
      dtype='object', name='Exterior1st')
Index(['AsbShng', 'Wd Sdng', 'Stucco', 'MetalSd', 'Wd Shng', 'HdBoard',
       'Rare_var', 'Plywood', 'BrkFace', 'CmentBd', 'VinylSd'],
      dtype='object', name='Exterior2nd')
Index(['BrkCmn', 'None', 'BrkFace', 'Rare_var', 'Stone'], dtype='object', name='MasVnrType')
Index(['Rare_var', 'TA', 'Gd', 'Ex'], dtype='object', name='ExterQual')
Index(['Fa', 'Rare_var', 'Gd', 'TA'], dtype='object', name='ExterCond')
Index(['Slab', 'BrkTil', 'CBlock', 'Rare_var', 'PConc'], dtype='object', name='Foundation')
Index(['Missing', 'Fa', 'TA', 'Gd', 'Ex'], dtype='object', name='BsmtQual')
Index(['Rare_var', 'Missing', 'Fa', 'TA', 'Gd'], dtype='object', name='BsmtCond')
Index(['Missing', 'No', 'Mn', 'Av', 'Gd'], dtype='object', name='BsmtExposure')
Index(['Missing', 'Rec', 'BLQ', 'LwQ', 'ALQ', 'Unf', 'GLQ'], dtype='object', name='BsmtFinType1')
Index(['Missing', 'BLQ', 'Rec', 'LwQ', 'Rare_var', 'Unf', 'ALQ'], dtype='object', name='BsmtFinType2')
Index(['Rare_var', 'GasW', 'GasA'], dtype='object', name='Heating')
Index(['Rare_var', 'Fa', 'TA', 'Gd', 'Ex'], dtype='object', name='HeatingQC')
Index(['N', 'Y'], dtype='object', name='CentralAir')
Index(['Rare_var', 'FuseF', 'FuseA', 'SBrkr'], dtype='object', name='Electrical')
Index(['Fa', 'TA', 'Gd', 'Ex'], dtype='object', name='KitchenQual')
Index(['Rare_var', 'Min2', 'Mod', 'Min1', 'Typ'], dtype='object', name='Functional')
Index(['Po', 'Missing', 'Fa', 'TA', 'Gd', 'Ex'], dtype='object', name='FireplaceQu')
Index(['Missing', 'Rare_var', 'Detchd', 'Basment', 'Attchd', 'BuiltIn'], dtype='object', name='GarageType')
Index(['Missing', 'Unf', 'RFn', 'Fin'], dtype='object', name='GarageFinish')
Index(['Missing', 'Fa', 'TA', 'Rare_var'], dtype='object', name='GarageQual')
Index(['Missing', 'Fa', 'Rare_var', 'TA'], dtype='object', name='GarageCond')
Index(['N', 'P', 'Y'], dtype='object', name='PavedDrive')
Index(['Missing', 'Rare_var'], dtype='object', name='PoolQC')
Index(['GdWo', 'Rare_var', 'MnPrv', 'GdPrv', 'Missing'], dtype='object', name='Fence')
Index(['Rare_var', 'Shed', 'Missing'], dtype='object', name='MiscFeature')
Index(['COD', 'Rare_var', 'WD', 'New'], dtype='object', name='SaleType')
Index(['Abnorml', 'Rare_var', 'Family', 'Normal', 'Partial'], dtype='object', name='SaleCondition')